version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
<<<<<<< HEAD

      - run: 
          name: Check flutter status
          command: flutter doctor

#      - run:
#          name: Run Flutter tests.
#          command: flutter test
=======
      - run: flutter doctor
      - run: flutter test 
>>>>>>> [FARM-170] Add Circle CI config file
